jobs:
    - name: job-hello-world
      public: true
      plan:
      - get: timer-2min
        trigger: true
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybbox}
          run:
            path: echo
            args: [hello world]

  resources:
  - name: timer-2min
    type: time
    source:
      interval: 2m
