jobs:
    - name: job-hello-world
      public: true
      plan:
      - get: timer-15min
        trigger: true
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybbox}
          run:
            path: echo
            args: [hello world]

resources:
  - name: timer-15min
    type: time
    source:
      interval: 15m

  - name: git-repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/szd55pilot/self-updating-pipeline-example.git
