jobs:
    - name: job-hello-world
      public: true
      plan:
      - get: timer-10min
        trigger: true
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybbox}
          run:
            path: echo
            args: [hello world]

    - name: configure-pipeline
      public: true
      plan:
        - get: self-update-pipeline
          trigger: true
        - set_pipeline: job-hello-world
          file: self-update-pipeline/pipelines/basic-pipeline.yml

resources:
  - name: timer-10min
    type: time
    source:
      interval: 10m

  - name: self-update-pipeline
    type: git
    icon: github-circle
    source:
      uri: https://github.com/szd55pilot/self-updating-pipeline-example.git
